### ISSUE TITLE
MODAL_DIRECTIVES not exported

### ISSUE THREAD

**Issue by alexkaskasoli** [dougludlow/ng2-bs3-modal-demo-systemjs#2]
Has this been fixed for the latest version of ng2-bs3-modal? I just `npm install`ed it but there's no MODAL_DIRECTIVES exported in `ng2-bs3-modal.js`

**Comment by dougludlow** [comment]
@alexkaskasoli, that's correct. MODAL_DIRECTIVES was removed in v0.8.0 as it is no longer needed with Angular2 rc6's new module system. The components and directives are exported with the Ng2Bs3ModalModule and then imported in you application's module.

**Comment by alexkaskasoli** [comment]
Thanks for the quick answer. I've answered an ongoing issue in the main ng2-bs3-modal repo. I'm getting `this.$modal.modal is not a function` even though jquery and bootstrap are loaded (and used elsewhere in the app without errors).

I guess this issue here can be closed though.

**Comment by dougludlow** [comment]
I see, I still need to update this repo to use the latest ng2-bs3-modal.
